Repository PixiEditor/PixiEditor, pull requests merged in 2020-12, with the labels that each got.

#107 Fixed sizeinput empty bug and aspect ratio infinite loop
  PixiEditor/Helpers/Behaviours/TextBoxFocusBehavior.cs
  PixiEditor/Views/UserControls/SizeInput.xaml
  PixiEditor/Views/UserControls/SizeInput.xaml.cs
  PixiEditor/Views/UserControls/SizePicker.xaml
Labels: bug

#117 Tabbed documents support
  PixiEditor/Models/Controllers/BitmapManager.cs
  PixiEditor/Models/Controllers/BitmapOperationsUtility.cs
  PixiEditor/Models/Controllers/ClipboardController.cs
  PixiEditor/Models/Controllers/UndoManager.cs
  PixiEditor/Models/DataHolders/Document.cs
  PixiEditor/Models/IO/Exporter.cs
  PixiEditor/Models/IO/Importer.cs
  PixiEditor/Models/Layers/Layer.cs
  PixiEditor/Models/Tools/Tool.cs
  PixiEditor/Models/Tools/Tools/MoveTool.cs
  PixiEditor/Models/Tools/Tools/MoveViewportTool.cs
  PixiEditor/Models/Tools/Tools/SelectTool.cs
  PixiEditor/Models/Tools/Tools/ZoomTool.cs
  PixiEditor/ViewModels/SubViewModels/Main/ClipboardViewModel.cs
  PixiEditor/ViewModels/SubViewModels/Main/DocumentViewModel.cs
  PixiEditor/ViewModels/SubViewModels/Main/FileViewModel.cs
  PixiEditor/ViewModels/SubViewModels/Main/IoViewModel.cs
  PixiEditor/ViewModels/SubViewModels/Main/LayersViewModel.cs
  PixiEditor/ViewModels/SubViewModels/Main/SelectionViewModel.cs
  PixiEditor/ViewModels/SubViewModels/Main/UndoViewModel.cs
  PixiEditor/ViewModels/SubViewModels/Main/ViewportViewModel.cs
  PixiEditor/ViewModels/ViewModelMain.cs
  PixiEditor/Views/MainWindow.xaml
  PixiEditor/Views/UserControls/DrawingViewPort.xaml
  PixiEditor/Views/UserControls/DrawingViewPort.xaml.cs
  PixiEditor/Views/UserControls/MainDrawingPanel.xaml.cs
  PixiEditorTests/ModelsTests/ControllersTests/BitmapManagerTests.cs
  PixiEditorTests/ModelsTests/ControllersTests/BitmapOperationsUtilityTests.cs
  PixiEditorTests/ModelsTests/ControllersTests/UndoManagerTests.cs
  PixiEditorTests/ModelsTests/DataHoldersTests/DocumentTests.cs
  PixiEditorTests/ModelsTests/ToolsTests/ZoomToolTests.cs
  PixiEditorTests/ViewModelsTests/ViewModelMainTests.cs
Labels: enhancement

#118 Added PixiParser
  PixiEditor/Helpers/Extensions/ParserHelpers.cs
  PixiEditor/Models/IO/Exporter.cs
  PixiEditor/Models/IO/Importer.cs
  PixiEditor/PixiEditor.csproj
  PixiEditor/ViewModels/SubViewModels/Main/FileViewModel.cs
  PixiEditor/ViewModels/ViewModelMain.cs
Labels: enhancement

#121 Removed tool enum
  PixiEditor/Images/FloodFillImage.png
  PixiEditor/Models/Controllers/BitmapOperationsUtility.cs
  PixiEditor/Models/Tools/ShapeTool.cs
  PixiEditor/Models/Tools/Tool.cs
  PixiEditor/Models/Tools/ToolType.cs
  PixiEditor/Models/Tools/Tools/BrightnessTool.cs
  PixiEditor/Models/Tools/Tools/CircleTool.cs
  PixiEditor/Models/Tools/Tools/ColorPickerTool.cs
  PixiEditor/Models/Tools/Tools/EraserTool.cs
  PixiEditor/Models/Tools/Tools/FloodFill.cs
  PixiEditor/Models/Tools/Tools/LineTool.cs
  PixiEditor/Models/Tools/Tools/MoveTool.cs
  PixiEditor/Models/Tools/Tools/MoveViewportTool.cs
  PixiEditor/Models/Tools/Tools/PenTool.cs
  PixiEditor/Models/Tools/Tools/RectangleTool.cs
  PixiEditor/Models/Tools/Tools/SelectTool.cs
  PixiEditor/Models/Tools/Tools/ZoomTool.cs
  PixiEditor/PixiEditor.csproj
  PixiEditor/ViewModels/SubViewModels/Main/ToolsViewModel.cs
  PixiEditor/ViewModels/ViewModelMain.cs
  PixiEditor/Views/MainWindow.xaml
  PixiEditor/Views/UserControls/DrawingViewPort.xaml
  PixiEditorTests/ModelsTests/ControllersTests/BitmapManagerTests.cs
  PixiEditorTests/ModelsTests/ControllersTests/BitmapOperationsUtilityTests.cs
  PixiEditorTests/ModelsTests/ControllersTests/MockedSinglePixelPenTool.cs
  PixiEditorTests/ModelsTests/ControllersTests/TestReadonlyTool.cs
  PixiEditorTests/ViewModelsTests/ViewModelMainTests.cs
Labels: enhancement, extension

#122 Colorpicker update
  PixiEditor/Models/Tools/Tool.cs
  PixiEditor/PixiEditor.csproj
  PixiEditor/ViewModels/SubViewModels/Main/SelectionViewModel.cs
  PixiEditor/ViewModels/SubViewModels/Main/UndoViewModel.cs
  PixiEditor/Views/MainWindow.xaml
Labels: enhancement

#123 Fixed removing logical focus from NumberInput
  PixiEditor/Helpers/Behaviours/ClearFocusOnClickBehavior.cs
  PixiEditor/Helpers/Behaviours/TextBoxFocusBehavior.cs
  PixiEditor/Views/Dialogs/ConfirmationPopup.xaml
  PixiEditor/Views/Dialogs/ImportFilePopup.xaml
  PixiEditor/Views/Dialogs/NewFilePopup.xaml
  PixiEditor/Views/Dialogs/ResizeCanvasPopup.xaml
  PixiEditor/Views/Dialogs/ResizeDocumentPopup.xaml
  PixiEditor/Views/Dialogs/SaveFilePopup.xaml
  PixiEditor/Views/Dialogs/SettingsWindow.xaml
  PixiEditor/Views/MainWindow.xaml
  PixiEditor/Views/UserControls/NumberInput.xaml
  PixiEditor/Views/UserControls/NumberInput.xaml.cs
Labels: bug
